

services:

  mysql:
    image: mysql:8.0
    container_name: hostel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hostel_complaints
      MYSQL_ROOT_PASSWORD: hostelpass123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-phostelpass123"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 40s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hostel-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hostel_complaints?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: hostelpass123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      GROQ_API_KEY: ${GROQ_API_KEY}
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hostel-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: